backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "entry"
    label: "Entry"
    folder: "content"
    format: json
    create: true
    identifier_field: name
    sortable_fields: [name]
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Intro Text", name: "introtext", widget: "text", required: false}
      - label: "Songs"
        name: "songs"
        widget: "list"
        summary: '{{fields.songname}} - {{fields.artistname}}'
        fields: 
          - {label: Song Name, name: songname, widget: string}
          - {label: Artist Name, name: artistname, widget: string}
          - {label: Link, name: link, widget: string}
          - {label: Description, name: description, widget: text, required: false}
          - label: Images
            name: images
            widget: "list"
            required: false
            fields:
              - {label: Image, name: image, widget: image, required: false, choose_url: true}
            


